### ISSUE TITLE
Service name already exists; misreported error, perhaps '&'

### ISSUE THREAD

**Issue by DRichey-LCDC** [Esri/workforce-scripts#100]
When trying to run script create_joined_view.py I receive the error  

[CRITICAL] Traceback (most recent call last): |   File "create_joined_view.py", line 457, in <module> |     main(args) |   File "create_joined_view.py", line 360, in main |     assignment_type_fields) |   File "create_joined_view.py", line 231, in create_joined_view |     "name": f"{name}" |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py", line 5453, in create_service |     snippet, |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_portalpy.py", line 555, in create_service |     resp = self.con.post(path, postdata) |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 1079, in post |     force_bytes=kwargs.pop("force_bytes", False), |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 607, in _handle_response |     raise Exception(data["error"]) | Exception: {'message': "Service name '('Reveg _ Invasive Veg Treatments Intermediate View 0 1650930822',)' already exists for 'qZ0lWJiFyXo3xsF1'"} |

I can find no view with the name Reveg _ Invasive Veg Treatments Intermediate View 0 1650930822 to delete. On speculation of illegal character, I edited the script to eliminate the ampersand in the source project name to no effect. the name is 62 characters, well less than the maximum 128 for a feature service.

I have run the script successfully on other workforce projects. None have '&' in the name.

To test, I created an empty WF project "Test & Go" This recieved the same error. While not conclusive, this indicats the ampersand is the likely culprit. As i already chagned the layer name for he output, I am not sure what othre modifications to make--perhpas the names of the input join layers?

here is the full eror for Test & Go
[2022-04-25 17:17:44,719] [         create_joined_view.py: 334 -                           main()]                [MainThread] [      root] [    INFO] Authenticating...
[2022-04-25 17:17:48,712] [         create_joined_view.py: 338 -                           main()]                [MainThread] [      root] [    INFO] Getting Workforce Project...
[2022-04-25 17:17:53,137] [         create_joined_view.py: 351 -                           main()]                [MainThread] [      root] [    INFO] Phase 1: Joining assignments to assignment types...
[2022-04-25 17:17:57,660] [         create_joined_view.py: 459 -                       <module>()]                [MainThread] [      root] [CRITICAL] Exception detected, script exiting
[2022-04-25 17:17:57,660] [         create_joined_view.py: 460 -                       <module>()]                [MainThread] [      root] [CRITICAL] {'message': "Service name '('Test _ Go Intermediate View 0 1650932273',)' already exists for 'qZ0lWJiFyXo3xsF1'"}
[2022-04-25 17:17:57,665] [         create_joined_view.py: 461 -                       <module>()]                [MainThread] [      root] [CRITICAL] Traceback (most recent call last): |   File "create_joined_view.py", line 457, in <module> |     main(args) |   File "create_joined_view.py", line 360, in main |     assignment_type_fields) |   File "create_joined_view.py", line 231, in create_joined_view |     "name": f"{name}" |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\__init__.py", line 5453, in create_service |     snippet, |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_portalpy.py", line 555, in create_service |     resp = self.con.post(path, postdata) |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 1079, in post |     force_bytes=kwargs.pop("force_bytes", False), |   File "C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3\lib\site-packages\arcgis\gis\_impl\_con\_connection.py", line 607, in _handle_response |     raise Exception(data["error"]) | Exception: {'message': "Service name '('Test _ Go Intermediate View 0 1650932273',)' already exists for 'qZ0lWJiFyXo3xsF1'"} |

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version: 3.7.11

**Additional context**

**Comment by apulverizer** [comment]
@DRichey-LCDC I can reproduce this and agree with your conclusions that the `&` is causing the issue. As a temporary workaround, you can modify lines 351, 360, 370, and 382 to use `project.title.replace('&','')` instead of `project.title`. 

Perhaps the service name needs to be urlencoded or something, I'll have to look into it more. Let me know if the workaround is okay for now.

**Comment by apulverizer** [comment]
I pushed a commit to the `master` branch that should resolve this.

**Comment by DRichey-LCDC** [comment]
Thank you, I appreciate it greatly. I had tried making the changes you suggested, but still received the error. Again, much appreciated. David
